---
- name: install apache
  apt: name=apache2 state=present

- name: Copy across new virtual host
  template:
    src=virtual-hosts.conf.j2
    dest=/etc/apache2/sites-available/vagrant.conf
  notify:
    - reload apache

- name: Remove default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache

- name: Enable new vagrant virtual host
  file:
    src=/etc/apache2/sites-available/vagrant.conf
    dest=/etc/apache2/sites-enabled/vagrant.conf
    state=link
  notify:
    - reload apache
- name: Output env vars
  shell: echo $PATH  
- git: repo=ssh@gitlab.com:neggs/ukfindit.com.git accept_hostkey=yes clone=yes key_file=/home/paje2/.ssh/id_rsa  
       executable="/usr/lib/git-core/git"
       dest=files/ukfindit.com
- name: Clean folders
  file: path=/var/www state=empty   
    
- name: Copy Website to /var/www
  copy:
    src=files/
    dest=/var/www
  notify:
    - reload apache

